baseurl = "http://blog.ralch.com/"
languageCode = "en-us"
title = "Svett Ralchev"

[Author]
	name = "Svett Ralchev"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "code by Nate Finch"
	twitter = "https://twitter.com/natethefinch"
	github = "https://github.com/natefinch"
  linkedin = "http://uk.linkedin.com/in/svettralchev"
	disqus = "ralch"

